language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

cache:
  directories:
  - $HOME/.m2

services:
  - mysql
  
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk7
  - # do stuff with Java 7
